version: 2
updates:
- package-ecosystem: npm
  directory: "/app"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@angular/compiler-cli"
    versions:
    - 11.0.5
    - 11.1.1
  - dependency-name: ionicons
    versions:
    - 5.2.3
    - 5.4.0
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
